### ISSUE TITLE
I had an error when installing, here's how to fix it.

### ISSUE THREAD

**Issue by duch11** [daviddietz/ynab-sdk#3]
## If you have trouble installing:
So when installing with `mvn install`, I got the following error: 

> "Error occurred during initialization of VM
> Could not reserve enough space for object heap"

### here is how I fixed it in Windows 10
Go to Start -> Control Panel -> System -> Advanced(tab) -> **Environment Variables -> System**

**Variables -> New: Variable**

```
name: _JAVA_OPTIONS
Variable value: -Xmx512M
```

[Link to original source of the solution](https://stackoverflow.com/questions/4401396/could-not-reserve-enough-space-for-object-heap#4401410)

**Comment by daviddietz** [comment]
Thanks for the tip. I will this to troubleshooting in the Readme.
